### ISSUE TITLE
Problems to get LIMIT keyword

### ISSUE THREAD

**Issue by fabiotabalipa** [klahnakoski/moz-sql-parser#1]
Hi there.

Firstly, I just one to point out that this project is awesome. I discovered it recently and I'm already using it in my code.

#### Issue

The query `SELECT * FROM jobs LIMIT 100` is retrivieng a dict without a key representing the LIMIT keyword: `{'select': '*', 'from': 'jobs'}`.

#### Code snippet

```python
import moz_sql_parser as msp

print(msp.parse('SELECT * FROM jobs LIMIT 10'))

> {'select': '*', 'from': 'jobs'}
````

#### Reproducing the behavior

These were the tested versions:
* 3.32.20026 (dev latest at this date)
* 3.125.20293 (latest at Mozilla master branch)

Thanks

**Comment by klahnakoski** [comment]
test added https://github.com/klahnakoski/moz-sql-parser/commit/0b927ae4d61b864fbf9cd0cff89ac8fc341060fb

**Comment by klahnakoski** [comment]
fixed on master, and deployed
