### ISSUE TITLE
Escape dots in aliases

### ISSUE THREAD

**Issue by pohmelie** [klahnakoski/moz-sql-parser#12]
Sources:
``` sql
select a.x as a.b.c.x from a
select a.x as "a.b.c.x" from a
```
Both parsed to:
``` json
{
    "select": {
        "value": "a.x",
        "name": "a.b.c.x"
    },
    "from": "a"
}
```

But, on sql side this two statements means different.

I faced this not on parsing, but formatting part. I need to make `a.b.c.d` alias to some column, but have no clue how to escape dots. I've found `\.` shadowing in formatter source code, but this leads to `\` character present in alias, since `.` replaced back with `\.` after escape on combine step.

**Comment by klahnakoski** [comment]
Thank you!   I know this bug, I was cheating at the time; I always wonder if the cheat will ever catch up to me.  It did.

I will get back to you here

**Comment by klahnakoski** [comment]
Tests added, and now pass.  It picked up an error in another test too.  Thank you!

https://github.com/klahnakoski/moz-sql-parser/commit/3557475eb9c85894dc3c971fcbd9509b7df99876#diff-5cdc87095af9dc76d067a08b883f9043c4d778ba719ddc61ec945520d0a73a1bR1866
