### ISSUE TITLE
"SELECT TOP 10" format used by t-sql is not supported

### ISSUE THREAD

**Issue by tiberiuichim** [klahnakoski/moz-sql-parser#13]
We'd like to use this library to format some dynamic queries, but the "TOP X" format is not used.

See this, for examples: https://www.w3schools.com/sql/sql_top.asp

**Comment by klahnakoski** [comment]
Thank you for this!  Let me look into this

**Comment by tiberiuichim** [comment]
@klahnakoski I've hacked a basic implementation in https://github.com/klahnakoski/moz-sql-parser/pull/14 (maybe minus the version change, I've tried to release a custom egg and forgot that the branch is in a PR).

And thank you for looking up and developing this package, it's a great thing.

**Comment by tiberiuichim** [comment]
@klahnakoski Another trouble spot in that PR, my editor is integrated with black and it autoformatted the files. Sorry! Though, for OS projects, it helps if there's a common ground that can be reused by all developers so that files are autoformatted the same way.

**Comment by klahnakoski** [comment]
And thank you for the PR!  I was not even going to consider the formatting, so you did a good thing there.  

On the subject of auto formatting: Each project has its own standards, or none at all.  For me, I do not care how the code is submitted: If it passes tests and is reasonably clean, then it is good.  Although, reformatted code is difficult to review on github: I will fetch it locally, and reformat, to reveal the true differences. I suggest you turn off the auto formatting on your editor: I think it is too soon for the whole world to have settled on a single Python format.

**Comment by klahnakoski** [comment]
I merged your code, and added handling for "percent" and "with ties".

**Comment by tiberiuichim** [comment]
A thousand thanks!
