### ISSUE TITLE
New failing test cases from a Redshift user

### ISSUE THREAD

**Issue by louisguitton** [klahnakoski/moz-sql-parser#5]
Next batch of failures on our 2800 (Redshift) SQL queries codebase after https://github.com/mozilla/moz-sql-parser/issues/149

My programmatic testing script
```python
from glob import glob
from tqdm import tqdm
from moz_sql_parser import parse, ParseException

sql_files = glob("models/**/*.sql", recursive=True)
print(len(sql_files))  # 2800

failures = []
with_cast_date = []
for f in tqdm(sql_files):
    with open(f, "r") as fh:
        query = fh.read()
    try:
        parse(query)
    except ParseException as e:
        failures.append(f)
        if ":: date" in query or "::date" in query:
            with_cast_date.append(f)

print(len(failures) / len(sql_files))  # 0.05714285714285714
print(len(with_cast_date) / len(sql_files))  # 0.04607142857142857
```

With the next 1️⃣ case, my estimation (using Regex) is that we can get this failure rate down to 1% on my codebase.
The rest of the cases are even more corner cases. I can definitely see the Pareto effect there. So fixing that one case would already be huge for my usage. I myself stop looking further in the long tail of failing queries for now 😁 

### `::` as `date`

```python
parse("select * from t left join ex on t.date = ex.date_at :: date""")
```
or 
```
parse("select distinct date_at :: date as date_at from t")
```
or 
```python
parse("""
    select
        datediff('day', u.birth_date :: date, us.date_at :: date) as day_diff
    from
        users as u
    inner join
        user_sessions as us
""")
```

### columns with special name

This one is scary to me.

Some of our columns from raw tables use reserved names, like `date`, so we rename them, for example to `date_at`. 

```python
parse("select date as date_at from t")
```
or 
```python
parse("""
select count(*) as validation_errors
from t
where date is null
""")
```
or
```python
parse("""
select count(*) as validation_errors
from t
where timestamp is null
""")
```

### `sum` window function

```python
parse("""
select
    salesid, 
    dateid, 
    sellerid, 
    qty,
    sum(qty) over (order by dateid, salesid rows unbounded preceding) as sum
from winsales
order by 2,1;
""")
```

Ref: https://docs.aws.amazon.com/redshift/latest/dg/r_WF_SUM.html#r_WF_SUM-examples

### `extract`

```python
parse("select extract('epoch' from occurred_at) as my_timestamp from t")
```
Ref: https://docs.aws.amazon.com/redshift/latest/dg/r_EXTRACT_function.html#r_EXTRACT_function-examples

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/moz-sql-parser/pull/6

**Comment by klahnakoski** [comment]
Thanks again for these detailed examples. 

https://pypi.org/project/moz-sql-parser/4.9.21002/

**Comment by louisguitton** [comment]
great job on this one 🚀 
I'm done to 1.7857% failing queries on the 2800 queries codebase 👏 that's very great for my usage and I'm happy with that.
I might open a follow-up issue if I can narrow down the remaining errors to something in particular.
