### ISSUE TITLE
New failing test cases from a Redshift user (part 3)

### ISSUE THREAD

**Issue by louisguitton** [klahnakoski/moz-sql-parser#7]
Testing the library on our 2800 Redshift SQL queries codebase, I'm down to 1.7857% failing rate. In this issue I collect the corner cases that currently fail.

This is my last batch of test cases. I went over each failing query in my codebase and they should all be covered by the cases below 🙏 .

Relates to : 
- https://github.com/klahnakoski/moz-sql-parser/issues/5
- https://github.com/mozilla/moz-sql-parser/issues/149

### `first_value ignore nulls`

special case for first_value and last_value window functions 

```python
parse("""
select venuestate, venueseats, venuename,
first_value(venuename ignore nulls)
over(partition by venuestate
order by venueseats desc
rows between unbounded preceding and unbounded following)
from (select * from venue where venuestate='CA')
order by venuestate;
""")
```
Ref:  last example of https://docs.aws.amazon.com/redshift/latest/dg/r_WF_first_value.html#r_WF_first_value-examples

### nested CTEs

```python
parse("""
with outer_cte as (
    with inner_cte as (
        select * from source
    )
    select date_at :: date from inner_cte
)
select * from outer_cte
""")
```

### `similar to`

```python
parse("""
select distinct city from users
where city similar to '%E%|%H%' order by city;
""")
```

Ref: https://docs.aws.amazon.com/redshift/latest/dg/pattern-matching-conditions-similar-to.html#pattern-matching-conditions-similar-to-examples

### mixed `union` and `union all`

```python
parse("""
select * from a
union
select * from b
union all
select * from c
""")
```

### `nvl` combined with `sum` window function

This works
```python
parse("""
select
    SUM(prev_day_count - line_count) over (order by date_at rows unbounded preceding) as dead_crons
from source
""")
```
This doesn't work
```python
parse("""
select
    NVL(
        SUM(prev_day_count - line_count) over (order by date_at rows unbounded preceding)
    , 0) as dead_crons
from source
""")
```

### `double precision` data type

```python
parse("select sum(price::double precision) as revenue from source")
```

Ref: https://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html#r_Numeric_types201-floating-point-types

### custom udfs

We use a few user defined functions (UDFs) which might take arbitrary names.
For example, `f_bigint_to_hhmmss` might convert a timestamp to a human readable time.
```sql
select f_bigint_to_hhmmss(device_timezone) from t
```
Given the names are arbitrary, what do you think is the best way to parse those corner case queries? Should I fork the repo and add to the grammar our custom function names? or is there a more generic way to handle functions that can be arbitrarily named?

Ref:
- https://docs.aws.amazon.com/redshift/latest/dg/udf-creating-a-scalar-sql-udf.html
- https://docs.aws.amazon.com/redshift/latest/dg/udf-creating-a-scalar-udf.html

**Comment by klahnakoski** [comment]
@louisguitton 

>Given the names are arbitrary, what do you think is the best way to parse those corner case queries? Should I fork the repo and add to the grammar our custom function names? or is there a more generic way to handle functions that can be arbitrarily named?

Any number of function names should be accepted by the parser already.

**Comment by klahnakoski** [comment]
I am still working on this *nvl combined with sum window function* has been giving me trouble.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/moz-sql-parser/pull/10

**Comment by klahnakoski** [comment]
https://pypi.org/project/moz-sql-parser/4.10.21011/

**Comment by louisguitton** [comment]
you rock @klahnakoski thanks a lot. I'll get back to hacking with it 🚀
